connector.name=iceberg
iceberg.catalog.type=JDBC
iceberg.jdbc-catalog.driver-class=org.postgresql.Driver
iceberg.jdbc-catalog.connection-url=jdbc:postgresql://postgres:5432/iceberg
iceberg.jdbc-catalog.connection-user=airflow
iceberg.jdbc-catalog.connection-password=airflow
iceberg.jdbc-catalog.catalog-name=stock_analytics
iceberg.jdbc-catalog.default-warehouse-dir=s3a://stock-data-lakehouse/iceberg-warehouse
